### ISSUE TITLE
Is there a way to have a review quotes appear on a book page but not be about that book? 

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#10]
We have great quotes that we want to appear on certain book pages without suggesting that the reviewer is commenting on that exact book?

**Comment by ndbooks** [comment]
Does this makes sense? 

I want to be able to make review quotes appear on book pages without it saying "about" the book in the q

**Comment by ndbooks** [comment]
Does this makes sense? 

I want to be able to make a quote appear on a book page without it saying "Tariq Ali on Beauty is a Wound" or whatever the book title is.

**Comment by budparr** [comment]
let me think about the best way to do this.

**Comment by ndbooks** [comment]
thank was a big complaint of old site

**Comment by budparr** [comment]
Do you want me to simply not show which book or author the quote is about if the quote appears on a book or other site
     attribution if it's not on an author or book page: "- James Joyce on X book"
     attribution if it is on an author or book page: "- James Joyce"

Or do you want more control than that.

**Comment by ndbooks** [comment]
Yes you can do that if I can then choose which page it appears on. That's
easy!

Also when I name the quote is that the name that it is attributed to. If so
will make it hard to search quotes. E.g. there will be a tonne that say
"New York Times" etc.

On Fri, Mar 20, 2015 at 1:18 PM, Bud Parr <notifications@github.com> wrote:

> Do you want me to simply not show which book or author the quote is about
> if the quote appears on a book or other site
> attribution if it's not on an author or book page: "- James Joyce on X
> book"
> attribution if it is on an author or book page: "- James Joyce"
>
> Or do you want more control than that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/10#issuecomment-84076783>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
well on each author and book page you choose the quotes and the order in which they appear, if that's what you mean.

And, yes, you're right - stupid of me. I was trying to save you from having too many fields to fill out, and in all databases, there's always a name field. The alternative is to have a descriptive name field (so and so on x book), but then a separate attribution field.

**Comment by ndbooks** [comment]
If there's one separate attribution field where I say "New York Times"
perhaps we could make it so there's flexibility there for me to also go on
and say "on blah blah". What do you think?

But there definitely needs to be one back-end search field that has key
words eg. "Aira NYT Musical Brain" and then the actually attribution "–*New
York Times*"

On Fri, Mar 20, 2015 at 1:39 PM, Bud Parr <notifications@github.com> wrote:

> well on each author and book page you choose the quotes and the order in
> which they appear, if that's what you mean.
>
> And, yes, you're right - stupid of me. I was trying to save you from
> having too many fields to fill out, and in all databases, there's always a
> name field. The alternative is to have a descriptive name field (so and so
> on x book), but then a separate attribution field.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/10#issuecomment-84084276>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
well the on blah blah has to be programatic because we link to the thing automatically

**Comment by ndbooks** [comment]
okay so no "blah blah" but just the person's name and/or publication and
then the link icon?

On Fri, Mar 20, 2015 at 1:43 PM, Bud Parr <notifications@github.com> wrote:

> well the on blah blah has to be programatic because we link to the thing
> automatically
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/10#issuecomment-84085804>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
Do you mean to say you don't want the programatic link, or are you saying leave things the way they are now, but give you a separate field for the attribution so that you can put whatever you want in the name field for internal identification?

**Comment by ndbooks** [comment]
OPTION 2 !

On Fri, Mar 20, 2015 at 1:57 PM, Bud Parr <notifications@github.com> wrote:

> Do you mean to say you don't want the programatic link, or are you saying
> leave things the way they are now, but give you a separate field for the
> attribution so that you can put whatever you want in the name field for
> internal identification?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/10#issuecomment-84088715>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
Okay. One last question. Do you feel as though I should change the existing name field to include more information now? That is, is it enough to do this for future quotes, or do you need it for all the past quotes.

**Comment by ndbooks** [comment]
I'm not sure what you mean. sorry bud. I just went cross eyed trying to get this

**Comment by budparr** [comment]
Nevermind
