### ISSUE TITLE
Do I have books that are forthcoming listed as 

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#11]

**Comment by budparr** [comment]
on the books page, which is, in fact, forthcoming

**Comment by budparr** [comment]
couple of questions:
How many new books (those that are out already) do you want to show?
Structurally, do you want:
```
New Books
- - - - - - - - 
Forthcoming Books
- - - - - - - - 
Bestsellers
- - - - - - - - 
```
or
```
New & Forthcoming Books
- - - - - - - - 
- - - - - - - - 
Bestsellers
- - - - - - - - 
```
Or something else entirely.

**Comment by budparr** [comment]
And let me know if you want to order the books there, or if you want me to just order them automatically by date (as they are now). Naturally, if you do it manually, you'll have to keep up with it, but either way is fine by me.

**Comment by ndbooks** [comment]
Dear Bud!

I think it looks great the way you have it now. ALTHOUGH can you do it
automatically by date but have them appearing in order from closet to pub.
Does that make sense?

But otherwise it's great.

On Thu, Mar 19, 2015 at 9:48 AM, Bud Parr <notifications@github.com> wrote:

> And let me know if you want to order the books there, or if you want me to
> just order them automatically by date (as they are now). Naturally, if you
> do it manually, you'll have to keep up with it, but either way is fine by
> me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/11#issuecomment-83588281>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
so, right now there's late poems, march 17th in first place. You want the forthcoming books show before that, - like, for instance, on the fiction page: http://ndbooks.webhook.org/books/fiction/

**Comment by ndbooks** [comment]
No no! Sorry, I wasn't clear.

I want Late Poems to appear first. Exactly as it is. Current order is
great.

And for the forthcoming books to stay where they are: after the new books.

BUT for the order of the forthcoming books to start in April, then May,
June, July etc. (at the moment it goes from September, then August, July)

On Thu, Mar 19, 2015 at 12:23 PM, Bud Parr <notifications@github.com> wrote:

> so, right now there's late poems, march 17th in first place. You want the
> forthcoming books show before that, - like, for instance, on the fiction
> page: http://ndbooks.webhook.org/books/fiction/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/11#issuecomment-83650425>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
okay. I'll close this issue in favor of the other one on that topic, and I'll figure out something to make it happen
