### ISSUE TITLE
Add "featured switch to show only important events on the home page

### ISSUE THREAD

**Issue by budparr** [newdirections/www.ndbooks.com#14]
FYI, @ndbooks - when you add an event it will only show up on the home page if you click the "Featured" switch. No need to switch it off later or anything (they'll go away after the event whenever the site is built). It's just there so we only show the best events there.

**Comment by ndbooks** [comment]
Hey BUD !

Is there a way that we can "feature" pictures from tumblr or instagram in the same way. For example we have this great pic now of Cesar Aira and Cecil Taylor on social media, but it doesn't work as a standalone blog post... 

https://instagram.com/p/0ZDLGku0Au/

**Comment by budparr** [comment]
Absolutely - the home page is designed so you can show anything there. I can add this for you, though it's not photographically great, so I can make it small. Note that everything on the home page links to something, so I guess for this we'd link it to the author page.

**Comment by budparr** [comment]
you're going to get tired of me being tyrannical about image quality and designy things!

**Comment by ndbooks** [comment]
ok! I hear you!
