### ISSUE TITLE
Do I have to make sure all forthcoming book are NOT for sale? 

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#15]
and then go back and make them for sale when they pub?

**Comment by budparr** [comment]
I just marked the issue with a question label so we can discuss when we next meet, if need be. 

The logic I used is to determine if something gets buy buttons:
1) A book has to have an "edition"
2) A book has to be marked "for sale" (which is the default, so normally won't be anything active on your part, so it's really more like not not for sale)
3) Has to have an ISBN.

If those three qualifications are met seems like there's no reason for the buy buttons to not be there. For instance, I see that for the Mr. Kafka book, it's available for pre-order on the retailers, so no harm in having a buy button.

Sound right?

**Comment by budparr** [comment]
By the way - all this stuff is designed to give you a balance between control and automation. In particular, designed in such a way that automates a lot of stuff so it operates without too much intervention, but then allowing for overrides to give you more control. It's a tricky balance.
