### ISSUE TITLE
Could we have a tab key or indent function in text boxes? 

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#16]
Otherwise messes with all the spacing...

**Comment by budparr** [comment]
Can you point to, specifically, where you're having a problem? You should be able to just hit your tab key on the keyboard for indents.

**Comment by ndbooks** [comment]
![screen shot 2015-03-20 at 4 56 35 pm](https://cloud.githubusercontent.com/assets/10980123/6760743/17d9b19e-cf22-11e4-8b59-6392fa96c232.png)

But I can just hit space five times...

**Comment by budparr** [comment]
me not follow you. you should be able to hit the tab key on your keyboard, or are you saying that's too much of an indent? even if we had a button, it would likely still indent by the same amount as the tab key

**Comment by ndbooks** [comment]
not it moves the whole text across. there is not way to tab just one line
and indent it. it skids out

On Fri, Mar 20, 2015 at 4:59 PM, Bud Parr <notifications@github.com> wrote:

> me not follow you. you should be able to hit the tab key on your keyboard,
> or are you saying that's too much of an indent? even if we had a button, it
> would likely still indent by the same amount as the tab key
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/16#issuecomment-84143599>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
you mean you're trying to indent the first line?

**Comment by ndbooks** [comment]
Yes!

On Fri, Mar 20, 2015 at 5:04 PM, Bud Parr <notifications@github.com> wrote:

> you mean you're trying to indent the first line?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/16#issuecomment-84145169>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
Unfortunately, that's a typographical no-no. You either indent the first line and have no spaces between paragraphs, or spaces between paragraphs and no indent. The former is good for print, not so much for the web.
