### ISSUE TITLE
Please change it so when you hover over a button it becomes more visible not less

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#18]
Hi Bud, 

Can we please make it so when you highlight one of the buttons in the top nav and in the various search options on the books pages that the button you are hovering over gets lighter or brighter not darker?

**Comment by budparr** [comment]
Yes. I was just working on this a bit yesterday. The styling for that got a bit complicated with the themes that I created, but shouldn't be a problem to get them straightened out.
