### ISSUE TITLE
Blog changes

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#19]
Hi Bud, 
I know that blog is not the top priority but I don't think we should launch until it works because it will get a lot of scrutiny. I'm going to work on content now. 

As a temporary fix I think we need to at least hide or change the blog history squares that appear down the bottom, after the featured blog posts. It looks like a glitch right now. 

More permanent CHANGE to this kind of excerpt style view: 
http://www.theparisreview.org/blog/
http://www.nybooks.com/blogs/nyrblog/
Will be so great! 

Also will there be away to view larger versions of pictures embedded in the blog? I feel like that is a standard feature on most things now which leads to a very strong impulse to view everything BIG! 

Argh... sorry to bombard. Hope you're not ready to knock your computer off the table.

**Comment by budparr** [comment]
Yeah, the blog was one of the first things I designed on the site and it doesn't even really look like the stuff I designed later. I'm happy to change it however you like. Specifically, with those comps, you mean , like PR, to display the posts like a "traditional" blog (like we have now on the old nd site, actually) with one full post after another, paginating after, say, 10 posts? Or, the second, showing longish excerpts of each post down the page (still traditional blog, but excerpts rather than full posts).

**Comment by ndbooks** [comment]
Definitely the latter! 

Showing longish excerpts of posts down the page that you can "read more" to take you to individual blog post page... Also with the option to view "older entries" the traditional way..

**Comment by budparr** [comment]
okay, I think I have a sense of what to do.

**Comment by ndbooks** [comment]
Dear Bud, 

The blog looks fantastic! 

I have a few thoughts though:

1) I think the whole page looks really dark. Can we make it the same white as the resources page content box? 

2) The blog post heading for each post needs to go above the feature image for each post. It's too confusing otherwise. 

3) Can we please remove the colored events boxes on the side? I think they're distracting. 

4) Is there another way to make the twitter feed work? The black is hard to read... 

5) Please add instagram to the social box. Also, don't hate me, but I still find all the color a bit jarring. Can we make it thinner or something...? 

Thanks so much!!!!!

**Comment by budparr** [comment]
can you drop by my office this afternoon? I'm at my "other" office, on 20th and 5th ave. Seems like we should go through some things together.

**Comment by ndbooks** [comment]
2:30 pm?

On Mon, Mar 23, 2015 at 10:44 AM, Bud Parr <notifications@github.com> wrote:

> can you drop by my office this afternoon? I'm at my "other" office, on
> 20th and 5th ave. Seems like we should go through some things together.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/19#issuecomment-85030584>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
Perfect. If you click on the address on the top of this page, there's a map. It's on the second floor.
http://civichall.org/a-new-home-for-civic-technology/
