### ISSUE TITLE
Series option is not clickable when creating new book page 

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#21]
Just tried to make Looking at Pictures a Christine Burgin co-pub but the series button isn't working

**Comment by budparr** [comment]
you mean in the control panel?

**Comment by ndbooks** [comment]
yep when I'm entering a new book

On Fri, Mar 20, 2015 at 4:02 PM, Bud Parr <notifications@github.com> wrote:

> you mean in the control panel?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/21#issuecomment-84130265>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
It's working for me - I just put it in for you. What exactly is happening when you put it in.

**Comment by ndbooks** [comment]
this is what I can see
![screen shot 2015-03-20 at 4 19 02 pm](https://cloud.githubusercontent.com/assets/10980123/6760193/e10a2b4e-cf1c-11e4-95b9-8d83bb119763.png)

**Comment by budparr** [comment]
Ah, I see. Once again, it's my idiocy at work here. Should be fixed now.
