### ISSUE TITLE
how do you make a book a "bestseller" or appear on the history page

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#26]
Here's what I can see but the "create" option is making me think this is the wrong place...? ?? 
![screen shot 2015-03-24 at 4 58 55 pm](https://cloud.githubusercontent.com/assets/10980123/6812742/2d6dc09a-d247-11e4-80b6-a247f3c21bde.png)

**Comment by budparr** [comment]
it's in the "--global--" section. Second list down. I may change that sometime soon

**Comment by ndbooks** [comment]
![screen shot 2015-03-26 at 4 49 56 pm](https://cloud.githubusercontent.com/assets/10980123/6856718/2fa8b724-d3d8-11e4-849f-85ce4912baf0.png)

**Comment by ndbooks** [comment]
is this how you do it? By typing "New Directions Publishers" into the global field ??

**Comment by budparr** [comment]
sorry, I hadn't given you access to the global section, but you should have it now. So it's in --global--
