### ISSUE TITLE
Please change site name from New Directions Publishers to "New Directions Publishing" OR "www.ndbooks.com"

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#27]
Also the little icon/pic (what do you call it? Sorry) is really fuzzy on my comp. Even on my nice new laptop... Can we do anything about that?

**Comment by budparr** [comment]
I made the change, should show up soon. I noticed that too about the icon. I made it for iPhone icons (so you can save the site to your home screen) but they have more detail than will show up. I'll make a separate issue for it. Back to my meeting!
