### ISSUE TITLE
Can I have access to change to themes? 

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#29]
In particular I want to change the resource page to the black and white theme so I can use that great bookshelf pic as the banner

**Comment by budparr** [comment]
try it now. Your LK/CA photo is not working out too well, I see. And poor poor Norman. So beautiful yet so touchy!

**Comment by ndbooks** [comment]
oh dear! Hmmm... there's no way to make it the thumbnail pic on the homepage but not the banner. Is there?

**Comment by budparr** [comment]
but it's whacky on the home page (if by home page you mean blog home page) too. You can send me the images and I'll see if I can help. You can just drop them right in this issue, or send via email.

**Comment by budparr** [comment]
If you just make their faces line up on the original you should be fine, though you might want to make it generally more horizontal.
![screen shot 2015-03-26 at 4 24 35 pm](https://cloud.githubusercontent.com/assets/115347/6856193/a49235dc-d3d4-11e4-9c0b-61b14c4f2461.png)
