### ISSUE TITLE
Can we link the image for the featured blog posts as well as the title on the homepage? 

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#30]
the desire to do this is really strong when browsing the homepage...

**Comment by budparr** [comment]
not following

**Comment by ndbooks** [comment]
![screen shot 2015-03-26 at 4 47 15 pm](https://cloud.githubusercontent.com/assets/10980123/6856663/e16bad82-d3d7-11e4-8fde-c489d89126a3.png)

**Comment by ndbooks** [comment]
the pics aren't links only the text

**Comment by budparr** [comment]
Oh, right. I'm going to change the label and add this to my todo queue.
