### ISSUE TITLE
Does the feature/banner image have to appear again in a post? 

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#33]
It looks funky.... 
Sorry Bud. Check out the Man Booker one for instance. I don't want the photo to appear again at the bottom of the post.

**Comment by ndbooks** [comment]
another example: http://www.ndbooks.com/article/love-hotel-at-mcnally-jackson/

**Comment by ndbooks** [comment]
http://www.ndbooks.com/article/a-desk-in-moscow/

**Comment by budparr** [comment]
Yeah, the only reason I left it in is that the one on top is constrained, but I guess if you wanted a full version of that image you could just put it in again. I change it.
