### ISSUE TITLE
LANGUAGE FIELD TYPO: PORTUGUESE

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#36]
Portuguese is spelt wrong. The Lispector translator pinched me about it this morning. Eeek!

**Comment by budparr** [comment]
Hope you blamed it on your illiterate developer.

**Comment by ndbooks** [comment]
as you advised... ha

On Mon, Mar 30, 2015 at 1:35 PM, Bud Parr <notifications@github.com> wrote:

> Hope you blamed it on your illiterate developer.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/36#issuecomment-87765624>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
fixed. will show up  soon.
