### ISSUE TITLE
Need to attribute books to authors when those books appear on the translator or editor's page

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#37]
Right now on a translator or editor's page the book just comes up under their name. I know that it is categorized as the top but it's a little misleading. 

Especially when there are two authors like for: 

Two American Scenes
Two Crocodiles 

What can we do about this? Eliot sent me a big email about it will be hard to get away with... 

Hi Bud!

**Comment by ndbooks** [comment]
Also, when someone (Eliot) is the editor AND the translator for a book the site gets confused. 

Check it out: http://www.ndbooks.com/author/eliot-weinberger/

The second lot of "translated by" should actually be "edited and translated by"

**Comment by budparr** [comment]
I'm not following, it seems to me that this is clear:
![screen shot 2015-03-30 at 1 31 18 pm](https://cloud.githubusercontent.com/assets/115347/6902324/177a526e-d6e1-11e4-9509-cebc6ba419f0.png)

**Comment by budparr** [comment]
though not sure why translator shows first, but I don't understand the complaint

**Comment by budparr** [comment]
And this seems clear to me
![screen shot 2015-03-30 at 1 33 33 pm](https://cloud.githubusercontent.com/assets/115347/6902360/66f16e22-d6e1-11e4-898a-3f20d71377b7.png)

**Comment by ndbooks** [comment]
The second lot of "As translator" books need to be "Editor and translator"
that's why they are showing up twice

On Mon, Mar 30, 2015 at 1:33 PM, Bud Parr <notifications@github.com> wrote:

> though not sure why translator shows first, but I don't understand the
> complaint
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/37#issuecomment-87763675>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by ndbooks** [comment]
He means when you scroll down to the book, depending on the cover, it's not clear who the author is... it just appears on the page without being attributed to the author. E.g. for Eliot it does not say "by Octavio Paz" or "by Bei Dao" or "with Lydia Davis" 

does that make sense? 

http://www.ndbooks.com/author/eliot-weinberger/

**Comment by budparr** [comment]
I understand, but it doesn't make sense to put that information there - it would just clutter up the page - what goes there is the synopsis and buy buttons, and if someone needs to "figure out" who the author is when they're on the page, they can simply click through to the page about the book. It's simply too much information and is being overthought here and not giving readers any credit for being smart enough to figure out who wrote it.

**Comment by ndbooks** [comment]
okay. I basically agree with this...  will put it to him.

But the editor/translator problem remains a bit of a bugger


On Mon, Mar 30, 2015 at 1:46 PM, Bud Parr <notifications@github.com> wrote:

> I understand, but it doesn't make sense to put that information there - it
> would just clutter up the page - what goes there is the synopsis and buy
> buttons, and if someone needs to "figure out" who the author is when
> they're on the page, they can simply click through to the page about the
> book. It's simply too much information and is being overthought here and
> not giving readers any credit for being smart enough to figure out who
> wrote it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/37#issuecomment-87768062>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
I changed the second one to editor, which is how it is in the background


—

**Comment by budparr** [comment]
And I certainly appreciate the feedback, but, you know, writers gotta write and designers gotta design.

**Comment by budparr** [comment]
I'm uploading the rest of the editor fix now, so the editors contributors will show up properly on the book pages.

**Comment by budparr** [comment]
and you can tell me if this is the copy you want for contributors
![screen shot 2015-03-30 at 5 49 33 pm](https://cloud.githubusercontent.com/assets/115347/6907551/2f20f048-d705-11e4-8ecd-c646003b03f7.png)
http://www.ndbooks.com/book/new-collected-poems/

**Comment by ndbooks** [comment]
The most ideal situation is if we could have three options:

Introduction by ...
Afterword by....
Contribution by...

The contribution by thing is only necessary for art content. For almost
every other instance it refers either to an intro of afterword. Is that
painful?

Otherwise what you have is fine. But the IDEAL is the above.

M

On Mon, Mar 30, 2015 at 5:50 PM, Bud Parr <notifications@github.com> wrote:

> and you can tell me if this is the copy you want for contributors
> [image: screen shot 2015-03-30 at 5 49 33 pm]
> <https://cloud.githubusercontent.com/assets/115347/6907551/2f20f048-d705-11e4-8ecd-c646003b03f7.png>
> http://www.ndbooks.com/book/new-collected-poems/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/37#issuecomment-87842384>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
That adds a structure/additional two fields, which seems like a lot to me. I think we need to find a creative solution. First thought is to just change the copy to either something inclusive or more generic. Second thought is to skip the relationship field for contributors altogether and give you a single line text field where you can write in whatever you like, and manually put in the link if need be. I don't think the manual link would be hard, and it would free up the space for whatever copy is necessary, have less structure, and allow you to list contributors that aren't entered into the site (like why have an entire page for Nicole Kraus? (who, by the way, doesn't appear to be linked to anything right now))






—
