### ISSUE TITLE
Restore full review names ? 

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#41]
Hi Bud, 

Okay this will be the last peep out of me for the day, but an unforseen problem of the slick review-view is that I can't pick review quotes for books. I have to take a wild guess as to which of the trillion "New York Times" attribute reviews is specific for the book page I am trying to add it to. Same goes for PW, Kirkus, Harpers etc. etc. etc. I can make the names more specific from now on but that doesn't help me with all the ones that are already there... 

Can we somehow restore or lengthen the review titles?

**Comment by budparr** [comment]
I don't really think so, unfortunately. If I brought the fields together it would look like "New Yorker on book -Jwyekjoufweyw23sus"
