### ISSUE TITLE
How to make blog post links appear with image on Facebook??? 

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#42]
Normally if you post a link that has a decent image it shows up. but with the new blog it just shows the headline. This makes a big difference to the dreaded clicks, likes, blah.... 

Not urgent, but important.

**Comment by budparr** [comment]
It's actually on the top of my list (and the only thing I have scheduled to try and get done before my vacation)

**Comment by ndbooks** [comment]
THANKS BUD!

**Comment by ndbooks** [comment]
CoooL!

On Tue, Mar 31, 2015 at 3:37 PM, Bud Parr <notifications@github.com> wrote:

> It's actually on the top of my list (and the only thing I have scheduled
> to try and get done before my vacation)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/42#issuecomment-88220725>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks
