### ISSUE TITLE
HELP! Counternarratives isn't showing up

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#43]
Counternarratives is not coming up. It says "book not found" or "create Counternarratives" when the book is definitely there and up on the site. really important as Michael got fired so now I have to promote this book like an insane person. please help!

**Comment by ndbooks** [comment]
![screen shot 2015-04-17 at 4 18 08 pm](https://cloud.githubusercontent.com/assets/10980123/7210154/5a7e7e74-e51d-11e4-9ee0-7f571cca1382.png)

**Comment by ndbooks** [comment]
OMG so i figured it out. It doesn't recognize lower case. Please can we change that. I nearly did myself a psychic injury. 

Thanks, Bud! Hope you're well.

**Comment by ndbooks** [comment]
Ok so it's still not working. I can't attribute quotes to the page

**Comment by budparr** [comment]
> Michael got fired

uh, what?
