### ISSUE TITLE
Books show up multiple times if someone contributed in more than one way

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#44]
How can we fix this? 

For example: if Eliot is the introducer AND the editor AND the translator the same book shows up when you scroll THREE times. Looks like a glitch or like sanity is slipping away... 

HalP? 

Also: HI BUD! HOW ARE YOU????

**Comment by budparr** [comment]
Howdy - hope you had nice travels. Well, anyway we explicitly link someone to a book, they're going to be linked. I'm not sure what the solution is, unless you wanted them to be listed all lumped together (

i.e. 
"as introducer, translator, or editor"

)
but that's not very good for most people. 

Are there a lot of people who have three roles on one book?
