### ISSUE TITLE
Please fix Italics glitch on BECAUSE SHE NEVER ASKED books page

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#45]
mysterious italics on this books page: http://www.ndbooks.com/book/because-she-never-asked/

**Comment by budparr** [comment]
Here's the culprit:

```
A novella–half jokes and half nightmare–by  
 "Spain's most significant contemporary literary figure" (<em>The New Yorker<em/>) 
```
spot it?
the closing ```</em>``` tag is written as ```<em/>```

However, I should note (and I'll put instructions on the field about this), that to italicize you merely need to put asterisks around the world like

``` *The New Yorker*```

I'll make the change for you now.

**Comment by ndbooks** [comment]
Lesson learned, bud!

On Thu, Apr 30, 2015 at 3:57 PM, Bud Parr <notifications@github.com> wrote:

> Here's the culprit:
>
> A novella–half jokes and half nightmare–by
>  "Spain's most significant contemporary literary figure" (<em>The New Yorker<em/>)
>
> spot it?
> the closing </em> tag is written as <em/>
>
> However, I should note (and I'll put instructions on the field about
> this), that to italicize you merely need to put asterisks around the world
> like
>
> *The New Yorker*
>
> I'll make the change for you now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/45#issuecomment-97949943>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
No worries. And, one more thing. Good to try and use typographically correct quote marks when you can. On a mac that's ```option-{``` for the left and ```option-shift-{``` for the right. I'll see if I can dig up a cheat sheet for you on this. I just saw one recently.

**Comment by budparr** [comment]
[typewolf_typography_cheatsheet.pdf | uploaded via ZenHub](https://files.zenhub.io/55428a2f9ed456506436d347)
