### ISSUE TITLE
Need to be able to have italics on or off in a featured quote on homepage

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#46]
almost every quote has a book title in it which needs to be no in italics if the quote is. Can it be done? 

HI BUD!

**Comment by budparr** [comment]
Hi there. 

Just put an asterisk around the book title, like this:

 ```The book title is *Wuthering Heights* a masterpiece```

which will display like this: 

The book title is *Wuthering Heights* a masterpiece

**Comment by budparr** [comment]
what's going on with the home page?
