### ISSUE TITLE
homepage formatting help

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#50]
doesn't look right... what am I doing wrong??? where are the alignment options? 

sorry bud

http://www.ndbooks.com/

**Comment by budparr** [comment]
Hiya - nice to see you yesterday. Fun party, as always. 

Can you be more specific? 

I fixed the text formatting on the Boyd Tonkin (should show up soon). It had some artifacts from being pasted in and the quote marks weren't typographically correct.

**Comment by budparr** [comment]
If you were talking about the fonts on the home page, I've cleaned them up for you. If it wasn't that, let me know.

The problem with the fonts is that when you copy/paste things into the editor, very often the formatting from the program gets carried over. It's best to either write in the content, or copy from plain text rather than something like Evil MS Word. I'm considering changing that editor to a markdown editor to eliminate that problem.

Also, I notice that on quotes there are sometimes quote marks and sometimes not. 

And, to be my pedantic-self: That bold lettering for such a big piece of text (The End of Days…) is a bit much, no?

**Comment by ndbooks** [comment]
Yes, it looks bad but I really need italics instead...

On Tue, Jun 2, 2015 at 3:24 PM, Bud Parr <notifications@github.com> wrote:

> If you were talking about the fonts on the home page, I've cleaned them up
> for you. If it wasn't that, let me know.
>
> The problem with the fonts is that when you copy/paste things into the
> editor, very often the formatting from the program gets carried over. It's
> best to either write in the content, or copy from plain text rather than
> something like Evil MS Word. I'm considering changing that editor to a
> markdown editor to eliminate that problem.
>
> Also, I notice that on quotes there are sometimes quote marks and
> sometimes not.
>
> And, to be my pedantic-self: That bold lettering for such a big piece of
> text (The End of Days…) is a bit much, no?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/50#issuecomment-108065761>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
Oh, funny. I see, it won't let you add italics within a heading. That's odd. I'll make a note to see if that's something that can be worked around. In the meantime, I added them for you. To do that, just hit the source button on the right and add:
```<em>around the words</em>```

**Comment by ndbooks** [comment]
oh I know that trick... thought it didn't work on the homepage for some
reason. thanks, bud. I don't need a button really now I know this, but
would be nice.

On Tue, Jun 2, 2015 at 3:31 PM, Bud Parr <notifications@github.com> wrote:

> Oh, funny. I see, it won't let you add italics within a heading. That's
> odd. I'll make a note to see if that's something that can be worked around.
> In the meantime, I added them for you. To do that, just hit the source
> button on the right and add:
> <em>around the words</em>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/50#issuecomment-108067889>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
well there is an italics button, it just, for some reason, doesn't allow you to add the italics to a heading.
