### ISSUE TITLE
Can I post a video to the blog? 

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#51]
Thanks, Bud!

**Comment by budparr** [comment]
Yep. YouTube? Just get the url of the video and click on the video button and paste it there.

**Comment by ndbooks** [comment]
not youtube a .mov
but I could upload it to youtube, I suppose...


On Mon, Jun 1, 2015 at 5:20 PM, Bud Parr <notifications@github.com> wrote:

> Yep. YouTube? Just get the url of the video and click on the video button
> and paste it there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/51#issuecomment-107716385>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
Yeah, totally youtube or Vimeo (I like Vimeo)
