### ISSUE TITLE
Unanimous desire for author names on book pages

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#54]
http://www.ndbooks.com/author/peter-cole/

**Comment by budparr** [comment]
should be live now

**Comment by ndbooks** [comment]
Dear Bud,

Did this really annoy you??? Sorry! Erik came in this morning with a list
of demands and I was trying to github them all before I forgot...


On Wed, Jun 3, 2015 at 11:49 AM, Bud Parr <notifications@github.com> wrote:

> Closed #54 <https://github.com/newdirections/www.ndbooks.com/issues/54>
> via e0e97de
> <https://github.com/newdirections/www.ndbooks.com/commit/e0e97de7b246cb9d91325871303bfedffa3bfa8e>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/54#event-321449907>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by ndbooks** [comment]
Dear Bud,

Can we just make it say "by blah blah" instead of "fiction by blah blah"
???

On Wed, Jun 3, 2015 at 11:50 AM, Bud Parr <notifications@github.com> wrote:

> should be live now
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/54#issuecomment-108493898>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
No (well the print thing, maybe). You've asked for this before. I feel it adds a lot of noise to the page, but I understand the need for it. 

I think it should have the genre. Those "modules" of book info can be in various places. They're on the home page as well as the books page, so I think as long as you're going to have more data you might as well have that as it's critical information. Don't you think so too?

**Comment by budparr** [comment]
I also made the book covers on those modules clickable, which I'd been meaning to do.
