### ISSUE TITLE
please make login for Erik!

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#55]
thank you!

**Comment by budparr** [comment]
what's his email address? You have to train him on using the system before he logs in.

**Comment by ndbooks** [comment]
That's cool. I won't fail you, BUd!

erieselbach@ndbooks.com

On Wed, Jun 3, 2015 at 11:57 AM, Bud Parr <notifications@github.com> wrote:

> what's his email address? You have to train him on using the system before
> he logs in.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/55#issuecomment-108496391>
> .
>



-- 
Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
mchew@ndbooks.com

ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks

**Comment by budparr** [comment]
He's going to get a funky email from "Webhook"
