### ISSUE TITLE
Asteriks still not working as ital in blog post header

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#60]
http://www.ndbooks.com/article/all-the-pictures-from-looking-at-pictures/

I am taking them out for now because it looks funny but would be great to fix. 

hi bud!

**Comment by budparr** [comment]
@ndbooks this is fixed

**Comment by ndbooks** [comment]
thanks!

On Thu, Nov 19, 2015 at 2:29 PM, Bud Parr <notifications@github.com> wrote:

> @ndbooks <https://github.com/ndbooks> this is fixed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newdirections/www.ndbooks.com/issues/60#issuecomment-158167781>
> .
>



-- 

Mieke Chew
New Directions Publishing
80 8th Avenue
New York, NY, 10011
(212-255-0230)
ndbooks.com
twitter.com/newdirections
facebook.com/ndbooks
