### ISSUE TITLE
Please change buying options for books. Replace Apple IBooks with Powell's

### ISSUE THREAD

**Issue by ndbooks** [newdirections/www.ndbooks.com#8]
Is this possible? Tom Roberge yelped about it.. 

http://www.powells.com/

**Comment by budparr** [comment]
Really? iBooks is for ebooks and Powell's doesn't sell ebooks.

We have the Independent bookstore in there, quite prominently. This is essentially the same setup we've had for years, not sure why the change now, particularly since Powell's is inside baseball.
